name: Daily MongoDB Backup

on:
  schedule:
    - cron: "0 18 * * *" # 11:30 PM IST every day
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Secrets
        run: |
          echo "Workflow started"